# 请选择是否要使用mysql,不使用的话默认使用sqLite来储存信息
isUseMySql: true
# 用于mysql数据库链接
mysql:
  ip: 106.12.156.212
  port: 3306
  username: hanshuai
  password: abc956812056
  databasename: minecraft
# 数据库连接池初始大小和最大连接数(不懂就别动下面这俩个)
initSize: 8
maxActive: 10

# 是否启用登录系统
isUser: true
# 是否启用每个玩家加入/退出游戏消息提醒
isMessage: true
# 是否启用hat命令
isHat: true
# 是否启用help帮助
isHelp: true
# 是否启用tp系统
isTp: true
# 是否启用送礼物系统
isGift: true
# 是否启用pvp管理
isPvp: true
# 是否开启武林秘籍系统
isSecret: true
# 是否开启home
isHome: true
# 是否开启back
isBack: true
# 木牌支持彩色字
isSignChange: true
# 物品栏上方伤害显示
isShowDamage: true

# 是否进行插件使用统计(true的话会每俩小时发送一个插件使用信息到统计网站)
isReport: true