#---------------------------需要mysql功能start---------------------------
# 是否启用登录系统(如果使用请填好mysql.yml)
isUser: true
# 是否启用每个玩家加入/退出游戏消息提醒(如果使用请填好mysql.yml)
isMessage: true
# 用于mysql数据库链接
mysql:
  ip: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  databasename: minecraft
#---------------------------需要mysql功能end---------------------------

# 默认全部玩家加入游戏欢迎语句
joinMessage: 欢迎 ${player} 加入服务器
# 默认全部玩家离开游戏欢迎语句
quitMessage: ${player} 离开了服务器
# tpa传送延迟时间(单位秒)
tpaDelayTime: 3
# tpa传送等待时间(单位秒)
tpaWaitTime: 30
