# 请选择是否要使用mysql,不使用的话默认使用sqLite来储存信息
isUseMySql: false
# 用于mysql数据库链接
mysql:
  ip: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  databasename: minecraft
# 数据库连接池初始大小和最大连接数(不懂就别动下面这俩个)
initSize: 8
maxActive: 10

# isUse是否开启该功能,permission权限设置:true给玩家该指令权限,false不给玩家该指令权限
# 是否启用登录系统
isUser:
  isUse: true
# 是否启用每个玩家加入/退出游戏消息提醒
isMessage:
  isUse: true
  permission:
    msg: true
    msgAdmin: false
# 是否启用hat命令
isHat:
  isUse: true
  permission:
    hat: true
# 是否启用help帮助
isHelp:
  isUse: true
  permission:
    help: true
# 是否启用tp系统
isTp:
  isUse: true
  permission:
    tp: false
    tpa: true
# 是否启用送礼物系统
isGift:
  isUse: true
  permission:
    gift: false
# 是否启用pvp管理
isPvp:
  isUse: true
  permission:
    pvp: true
# 是否开启武林秘籍系统
isSecret:
  isUse: false
  permission:
    secret: true
    secretAdmin: false
# 是否开启home
isHome:
  isUse: true
  permission:
    setHome: true
    home: true
# 是否开启back
isBack:
  isUse: true
  permission:
    back: true
# 是否启用spawn
isSpawn:
  isUse: true
  permission:
    setSpawn: false
    spawn: true
# 木牌/聊天支持颜色代码&
isColor:
  isUse: true
# 物品栏上方伤害显示
isShowDamage:
  isUse: true
# 是否启用死亡惩罚
isDeathPenalty:
  isUse: true

# 是否进行插件使用统计(true的话会每俩小时发送一个插件使用信息到统计网站,异步运行不影响服务器)
isReport: true