# 用于mysql数据库链接
mysql:
  ip: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  databasename: minecraft
#需要开启的功能start------------------------
# 是否启用登录系统
isUser: true
# 是否启用每个玩家加入/退出游戏消息提醒
isMessage: true
# 是否启用hat命令
isHat: true
# 是否启用help帮助
isHelp: true
# 是否启用tp系统
isTp: true
# 是否启用送礼物系统
isGift: true
# 是否启用pvp管理和对应的粒子特效
isPvp: true
isPvpParticle: true
#需要开启的功能end--------------------------