name: manage
main: cn.handy.Manage
version: 4.1.3
author: handy
api-version: 1.13
permissions:
    handy.manage:
        default: op
    handy.tp:
        default: op
    handy.gift:
        default: op
    handy.msgadmin:
        default: op
    handy.msg:
        default: true
    handy.hat:
        default: true
    handy.pvp:
        default: true