name: manage
main: cn.handy.Manage
version: 2.1.1
author: handy
permissions:
    handy.tp:
        default: op
    handy.gift:
        default: op
    handy.msg:
        default: op
    handy.hat:
        default: true
