name: manage
main: cn.handy.Manage
version: 3.0.1
author: handy
permissions:
    handy.manage:
        default: op
    handy.tp:
        default: op
    handy.gift:
        default: op
    handy.msgadmin:
        default: op
    handy.msg:
        default: true
    handy.hat:
        default: true
    handy.pvp:
        default: true